### ISSUE TITLE
Header "x-jwt-assertion" value to replace with XXX

### ISSUE THREAD

**Issue by Valiantsin2021** [mobikylym/Allure-Test-Controller#1]
The "x-jwt-assertion" header value is returned in raw format (without masking) in the report HTML.

**Comment by mobikylym** [comment]
@Valiantsin2021 Good afternoon!
I added a replacement for this header in [the last commit](https://github.com/mobikylym/Allure-Test-Controller/commit/a5f95f5d8e59927002904520324e3356014f3c75). Please download the latest version and give me feedback.

**Comment by Valiantsin2021** [comment]
Hi @mobikylym! Thanks for quick response :)!

**Comment by mobikylym** [comment]
@Valiantsin2021 You are welcome!
If you have other ideas and suggestions for improving the plugin, I will be glad to consider them. Have a nice day)
